import Foundation
#if canImport(FoundationModels)
import FoundationModels

/// Assistant tool: produce an on-device market briefing over the symbols
/// StockSage is tracking, and surface any strong buy/sell signals. This is the
/// user-facing entry point for the integrated StockSage subsystem — ask the
/// assistant "give me a market briefing" or "any strong signals?" and it runs.
///
/// The briefing is generated by `StockSageBriefingService` (real `LocalLLM`
/// summary over deterministic, hallucination-free facts; offline fallback when
/// no brain is reachable). Data currently comes from `StockSageStore`'s sample
/// set — clearly labeled as sample until Chat A's live feed lands.
struct StockSageBriefingTool: Tool {
    let name = "market_briefing"
    let description = """
    Give an on-device market briefing for the user's tracked symbols, including \
    any strong buy/sell signals. Call this when the user asks about the market, \
    their watchlist, stock signals, or wants a market summary. Returns a concise \
    briefing computed locally (no external data is fetched). Note: until a live \
    price feed is connected, this operates on a small built-in SAMPLE set — say \
    so when presenting results.
    """

    @Generable
    struct Arguments {
        @Guide(description: "Optional focus, e.g. a specific ticker or 'only strong signals'. Leave empty for a full briefing.")
        var focus: String
    }

    func call(arguments: Arguments) async throws -> String {
        let symbols = await StockSageStore.shared.fetchAllSymbols()
        let isSample = await StockSageStore.shared.isSampleData
        let briefing = await StockSageBriefingService.generateBriefing(for: symbols)

        let prefix = isSample
            ? "⚠️ Sample data (no live feed connected yet):\n\n"
            : ""
        return prefix + briefing
    }
}
#endif
